on:
  push:
  pull_request:
jobs:
  test:
    name: Test monorepo
    runs-on: ubuntu-latest # ? Use a matrix for better tests?
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Create test-results directory
        run: mkdir -p test-results

      - name: Run simulation tests
        if: ${{ hashFiles('packages/simulation/**/*.test.*') != '' }}
        run: |
          bun test packages/simulation \
          --reporter=junit \
          --reporter-outfile=test-results/simulation.xml

      - name: Run runtime tests
        if: ${{ !cancelled() && hashFiles('packages/runtime/**/*.test.*') != '' }}
        run: |
          bun test packages/runtime \
          --reporter=junit \
          --reporter-outfile=test-results/runtime.xml

      - name: Run content tests
        if: ${{ !cancelled() && hashFiles('packages/content/**/*.test.*') != '' }}
        run: |
          bun test packages/content \
          --reporter=junit \
          --reporter-outfile=test-results/content.xml

      - name: Publish test report
        if: ${{ !cancelled() }}
        uses: dorny/test-reporter@v3
        with:
          name: Monorepo test results
          path: test-results/*.xml
          reporter: java-junit
