on:
  push:
  pull_request:
jobs:
  test:
    name: Test the whole monorepo
    runs-on: ubuntu-latest # ? Use a matrix for better tests?
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Install Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Run tests
        run: bun test
